name: test-users

on:
  pull_request:
    paths:
      - 'users/**'
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Shutdown Ubuntu MySQL (SUDO)
        run : sudo service mysql stop
      - name : Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: ${{ secrets.RootPassword }}
      - name: install dependencies and run test script
      
      - uses: actions/checkout@v2
      - run: cd users && npm install && npm run test:ci
     
    
    
