name: test-users

on:
  pull_request:
    paths:
      - 'users/**'
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - run : sudo service mysql stop
       
      -  uses: mirromutth/mysql-action@master
         with:
          mysql root password : ${{secrets.DB_TEST_PASSWORD}}
      - run: cd users && npm install && npm run test:ci 

    
